## 6-е домашнее задание - Библиотека numpy

<b>Выполнила:</b> Полиенко Анастасия Николаевна, НПМбд-01-19 (вторая подгруппа)


In [116]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [117]:
np.linspace(-1.3, 2.5, 64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [118]:
n = 10
np.tile([1, 2, 3], n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [119]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [120]:
A = np.zeros((10, 10))
A[:, 0] = 1; A[0, :] = 1; A[:, -1] = 1; A[-1, :] = 1
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [121]:
A = np.zeros((8,8))
A[::2,::2] = 1
A[1::2,1::2] = 1
print(A)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [122]:
def make_matrix(n):
    A = np.zeros((n, n))
    for i in range(n):
        A[i] = np.arange(i, i + n)
    return A
make_matrix(6)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  3.,  4.,  5.,  6.,  7.],
       [ 3.,  4.,  5.,  6.,  7.,  8.],
       [ 4.,  5.,  6.,  7.,  8.,  9.],
       [ 5.,  6.,  7.,  8.,  9., 10.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [123]:
V1 = np.arange(1,8,2)
V2 = np.arange(2,10,2)
A = np.arange(1,21).reshape(4,5)
B = np.arange(15,0,-1).reshape(5,3)
print('V1 · V2 =', V1.dot(V2))
print('V1 · A =', V1.dot(A))
print('A · B =', A.dot(B))

V1 · V2 = 100
V1 · A = [186 202 218 234 250]
A · B = [[105  90  75]
 [330 290 250]
 [555 490 425]
 [780 690 600]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [124]:
x = np.linspace(0,1,21)
cos_array = np.cos(x)
sin_array = np.sin(x)
np.array([np.array_str(cos_array), np.array_str(sin_array)])

array(['[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242\n 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452\n 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315\n 0.62160997 0.58168309 0.54030231]',
       '[0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396\n 0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723\n 0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041\n 0.78332691 0.8134155  0.84147098]'],
      dtype='<U235')

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [125]:
4 * np.random.rand(3,5) - 1

array([[-0.25165316,  1.97094833, -0.9982146 ,  0.20939956, -0.72993246],
       [-0.60967558,  0.94428884, -0.09269564,  1.45871169,  2.02733296],
       [ 0.22643795,  1.65388063,  2.09138058, -0.99688147, -0.01581007]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [126]:
A = np.array([[3, 7, 16, 16, 17],
              [5, 4, 19, 9, 11],
              [1, 10, 14, 4, 6],
              [2, 7, 17, 11, 9]])
print('Сумма всех элементов:', np.sum(A))
print('Сумма по строкам:', np.sum(A, axis = 1))
print('Сумма по стоблцам:', np.sum(A, axis = 0))
print('Среднее по строкам:', np.mean(A, axis = 1))
print('Дисперсия по строкам:', np.var(A, axis = 1))
print('Стандартное отклонение по строкам:', np.sqrt(np.var(A, axis = 1)))

Сумма всех элементов: 188
Сумма по строкам: [59 48 35 46]
Сумма по стоблцам: [11 28 66 40 43]
Среднее по строкам: [11.8  9.6  7.   9.2]
Дисперсия по строкам: [32.56 28.64 20.8  24.16]
Стандартное отклонение по строкам: [5.70613705 5.35163526 4.5607017  4.91528229]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [127]:
(A - np.array([np.mean(A, axis = 1),]).T) / np.array([np.sqrt(np.var(A, axis = 1)),]).T

array([[-1.5421992 , -0.84119956,  0.73604962,  0.73604962,  0.91129953],
       [-0.85955036, -1.04640913,  1.75647247, -0.11211526,  0.26160228],
       [-1.31558703,  0.65779351,  1.53485153, -0.65779351, -0.2192645 ],
       [-1.46481923, -0.44758365,  1.58688749,  0.36620481, -0.04068942]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [128]:
A[np.argsort(A[:, 2])]

array([[ 1, 10, 14,  4,  6],
       [ 3,  7, 16, 16, 17],
       [ 2,  7, 17, 11,  9],
       [ 5,  4, 19,  9, 11]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [129]:
B = A.T.dot(A)
print('B =', B)
print('Размер B:', end = ' ')
print(*B.shape, sep = 'x')
C = A.dot(A.T)
print('C =', C)
print('Размер C:', end = ' ')
print(*C.shape, sep = 'x')
f'У матриц В и С разные размерности, но они обе квадратные'

B = [[  39   65  191  119  130]
 [  65  214  447  265  286]
 [ 191  447 1102  670  718]
 [ 119  265  670  474  494]
 [ 130  286  718  494  527]]
Размер B: 5x5
C = [[859 678 463 656]
 [678 604 413 559]
 [463 413 349 408]
 [656 559 408 544]]
Размер C: 4x4


'У матриц В и С разные размерности, но они обе квадратные'

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [130]:
print('Сумма диагональных элементов B:', sum(np.diag(B)))
print('Сумма диагональных элементов C:', sum(np.diag(C)))

Сумма диагональных элементов B: 2356
Сумма диагональных элементов C: 2356


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [131]:
def check_det(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        return 'не определён'
    return np.linalg.det(matrix)
def check_eig(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        return 'не определён'
    v, w = np.linalg.eig(matrix)
    return v

print('Ранг матрицы A:', np.linalg.matrix_rank(A), 'Определитель матрицы А:', check_det(A))
print('Ранг матрицы B:', np.linalg.matrix_rank(B), 'Определитель матрицы B:', check_det(B))
print('Ранг матрицы C:', np.linalg.matrix_rank(C), 'Определитель матрицы C:', check_det(C))
print('Спектр матрицы А:', check_eig(A))
print('Спектр матрицы B:', *check_eig(B))
print('Спектр матрицы C:', *check_eig(C))

f'У матриц B и С совпадают собственные значения'

Ранг матрицы A: 4 Определитель матрицы А: не определён
Ранг матрицы B: 4 Определитель матрицы B: 4.1380531001777986e-08
Ранг матрицы C: 4 Определитель матрицы C: 32454882.000000022
Спектр матрицы А: не определён
Спектр матрицы B: 2240.7682403991225 79.11759560655446 30.01497611684876 7.260385389093256e-16 6.099187877474743
Спектр матрицы C: 2240.7682403991225 79.1175956065545 30.01497611684866 6.099187877474759


'У матриц B и С совпадают собственные значения'

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [132]:
np.random.seed(1032192921)
variant = np.random.randint(10)
print('Вариант:', variant)

Вариант: 9


In [133]:
def f(x):
    return (2 * x - 1) / (2 * x + 1)

In [134]:
def int_rectangle(f, a, b, step):
    x = np.linspace(a, b - step, int((b - a) / step))
    y = f(x) * step
    return np.sum(y)

In [135]:
def int_trapezium(f, a, b, step):
    x = np.linspace(a, b, int((b - a) / step) + 1)
    y = f(x[0]) + 2 * np.sum(f(x[1:-1])) + f(x[-1])
    return y * step / 2

In [136]:
def int_simpson(f, a, b, step):
    x = np.linspace(a, b, int((b - a) / step) + 1)
    y = f(x[0]) + 4 * np.sum(f(x[1:-1:2])) + 2 * np.sum(f(x[2:-1:2])) + f(x[-1])
    return y * step / 3

<b>Аналититическое решение:</b> $\int\limits_0^2 \frac{2x-1}{2x+1} dx = \int\limits_0^2 (1 - \frac{2}{2x+1})dx = \int\limits_0^2 dx - \int\limits_0^2 \frac{d(2x)}{2x+1} = 2 - \ln |2x + 1| |_0^2= 2 - \ln 5 \approx 0.390562087566$

In [138]:
print('Метод прямоугольников:', int_rectangle(f, 0, 2, 0.00001))
print('Метод трапеций:', int_trapezium(f, 0, 2, 0.001))
print('Метод Симпсона:', int_simpson(f, 0, 2, 0.01))
f'Метод Симсона требует меньше всего разбиений для достижения той же точности по сравнению с методом трапеций и прямоугольников'

Метод прямоугольников: 0.39055213474369765
Метод трапеций: 0.3905617675660328
Метод Симпсона: 0.3905620822461698


'Метод Симсона требует меньше всего разбиений для достижения той же точности по сравнению с методом трапеций и прямоугольников'